version: "3.10"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    container_name: human-resource-backend
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
