# Generated by Django 4.2.2 on 2023-07-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_app', '0002_rename_entry_time_timetrack_checkout_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_id',
            field=models.IntegerField(default='0', unique=True),
            preserve_default=False,
        ),
    ]
