# Generated by Django 4.2.2 on 2023-07-02 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_app', '0003_remove_employee_phone_employee_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_id',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_personal_id', message='Personal ID must be an 8-digit number.', regex='^[0-9]{8}$')]),
        ),
    ]
