# Generated by Django 4.2.2 on 2023-07-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_app', '0005_workhour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrack',
            name='checkout_time',
            field=models.DateTimeField(),
        ),
    ]
