# Generated by Django 4.2.2 on 2023-07-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_app', '0006_alter_timetrack_checkout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhour',
            name='hours_worked',
            field=models.FloatField(),
        ),
    ]
