# Generated by Django 4.2.2 on 2023-07-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_app', '0007_alter_workhour_hours_worked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhour',
            old_name='day',
            new_name='date',
        ),
    ]
