# Generated by Django 4.2.2 on 2023-07-03 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_app', '0008_rename_day_workhour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_id',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
