# Generated by Django 4.2.2 on 2023-07-03 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_app', '0009_alter_employee_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='-', max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_id',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
