# Generated by Django 4.2.2 on 2023-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_app', '0010_employee_phone_alter_employee_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='-', max_length=1),
            preserve_default=False,
        ),
    ]
