# Generated by Django 4.2.2 on 2023-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_app', '0011_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60, verbose_name='Token to blacklist')),
            ],
        ),
    ]
