# Generated by Django 4.2.2 on 2023-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_app', '0014_rename_text_feedback_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hour_wage',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
    ]
