# Generated by Django 4.2.2 on 2023-07-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_app', '0015_employee_hour_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrack',
            name='checkout_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
